POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 90d70255c4e3386da4aaaabc49d94e25add13ec2 

{
  "name": "string",
  "text": "string",
  "cooking_time": 1,
  "image": " data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
  "tags": [1],
  "ingredients": [45, 1134]
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "email": "kdemian@yandex.ru",
  "password": "demian"
}

###
GET http://127.0.0.1:8000/api/recipes/

###
GET http://127.0.0.1:8000/api/recipes/1/

###
DELETE http://127.0.0.1:8000/api/recipes/1/favourite/
Authorization: Token 90d70255c4e3386da4aaaabc49d94e25add13ec2 

###
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token 90d70255c4e3386da4aaaabc49d94e25add13ec2 


###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token 90d70255c4e3386da4aaaabc49d94e25add13ec2 

###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 90d70255c4e3386da4aaaabc49d94e25add13ec2 

###
GET http://127.0.0.1:8000/api/tags/

###
GET http://127.0.0.1:8000/api/tags/1/