POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "kdemian@yandex.ru",
  "username": "demian",
  "first_name": "demian",
  "last_name": "komarov",
  "password": "demian197"
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "email": "kdemian@yandex.ru",
  "password": "Demian197"
}

###
GET http://127.0.0.1:8000/api/recipes/

###
GET http://127.0.0.1:8000/api/recipes/demian
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/recipes/1/

###
POST http://127.0.0.1:8000/api/recipes/1/favourite/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
DELETE http://127.0.0.1:8000/api/recipes/1/favourite/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 


###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/users/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/users/2/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/tags/

###
GET http://127.0.0.1:8000/api/tags/1/

###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 
Content-Type: application/json

{
  "old_password": "demian197",
  "new_password": "Demian197"
}

### Subscribe on yourself (error)
POST http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65

###
POST http://127.0.0.1:8000/api/users/2/subscribe/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
DELETE http://127.0.0.1:8000/api/users/2/subscribe/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/users/subscribtions/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/users/?limit=1

###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/recipes/?is_in_favourite=1
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 

###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
Authorization: Token a58181e634dc57cf92fdae8c7dd74f2b5bc62d65 
