POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

###
PATCH  http://127.0.0.1:8000/api/recipes/1/
Content-Type: application/json
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

{
  "tags": [
    1
  ],
  "ingredients": [
    {
      "id": 345,
      "amount": 20
    },
    {
      "id": 902,
      "amount": 1
    }
  ],
  "name": "New name",
  "cooking_time": 2
}

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "kdemian@yandex.ru",
  "username": "demian",
  "first_name": "demian",
  "last_name": "komarov",
  "password": "demian197"
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "email": "kdemian@yandex.ru",
  "password": "demian"
}

###
GET http://127.0.0.1:8000/api/recipes/

###
GET http://127.0.0.1:8000/api/recipes/?author=1
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/recipes/1/

###
POST http://127.0.0.1:8000/api/recipes/1/favorite/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
DELETE http://127.0.0.1:8000/api/recipes/1/favorite/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 


###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/users/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/users/1/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/users/1/

###
GET http://127.0.0.1:8000/api/tags/

###
GET http://127.0.0.1:8000/api/tags/1/

###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 
Content-Type: application/json

{
  "old_password": "demian197",
  "new_password": "Demian197"
}

### Subscribe on yourself (error)
POST http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f

###
POST http://127.0.0.1:8000/api/users/2/subscribe/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
DELETE http://127.0.0.1:8000/api/users/2/subscribe/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/users/subscriptions/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/users/?limit=1

###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/recipes/?is_in_favorite=1
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/ingredients/?name=пше
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 

###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token f3bc8946c25c26e3023b5e34fbb01b54f0b2fe2f 
