# Generated by Django 4.1.6 on 2023-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('ingredient', models.ManyToManyField(to='recipes.ingredient')),
                ('recipe', models.ManyToManyField(to='recipes.recipe')),
            ],
        ),
    ]
