# Generated by Django 4.1.6 on 2023-02-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredientamount_ingredient_ingredient_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
