# Generated by Django 4.1.6 on 2023-02-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
