# Generated by Django 4.1.6 on 2023-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_recipes_favourite_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
