# Generated by Django 4.1.6 on 2023-02-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopping_cart',
        ),
    ]
