# Generated by Django 4.1.6 on 2023-02-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_ingredient_amount_ingredientamount_ingredient'),
        ('users', '0006_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='users', to='recipes.recipe'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
