# Generated by Django 4.1.6 on 2023-02-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_follow_unique follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
